"use client";

import { useMemo, useState } from "react";
import { Download, Eye, PackageCheck, ReceiptText, RotateCcw, Search, WalletCards, X } from "lucide-react";
import { formatRupiah, purchases } from "@/data/lwu";
import type { Purchase } from "@/types/lwu";

const statusStyle = { Successful: "bg-emerald-50 text-emerald-700 ring-emerald-600/10", Pending: "bg-amber-50 text-amber-700 ring-amber-600/10", Refunded: "bg-slate-100 text-slate-600 ring-slate-600/10" };

export function PurchaseHistoryView() {
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("All status");
  const [type, setType] = useState("All products");
  const [selected, setSelected] = useState<Purchase | null>(null);
  const [toast, setToast] = useState("");
  const filtered = useMemo(() => purchases.filter((purchase) => `${purchase.invoice} ${purchase.productName}`.toLowerCase().includes(query.toLowerCase()) && (status === "All status" || purchase.status === status) && (type === "All products" || purchase.productType === type)), [query, status, type]);
  const receipt = () => { setToast("Your receipt download has started."); setSelected(null); setTimeout(() => setToast(""), 2600); };
  const successfulTotal = purchases.filter((p) => p.status === "Successful").reduce((total, p) => total + p.amount, 0);

  return (
    <>
      <div className="mt-6 grid gap-4 md:grid-cols-3">
        {[{ label: "Total purchases", value: purchases.length.toString(), note: "All time", icon: WalletCards, color: "bg-sky-50 text-[#155EAA]" }, { label: "Successful", value: purchases.filter((p) => p.status === "Successful").length.toString(), note: "Completed payments", icon: PackageCheck, color: "bg-emerald-50 text-emerald-700" }, { label: "Total spent", value: formatRupiah(successfulTotal).replace("Rp", "Rp "), note: "Successful transactions", icon: ReceiptText, color: "bg-violet-50 text-violet-700" }].map(({ label, value, note, icon: Icon, color }) => <article key={label} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-2 text-2xl font-black tracking-[-.03em] text-[#0B2D5C]">{value}</p><p className="mt-2 text-[11px] text-slate-400">{note}</p></div><span className={`grid h-10 w-10 place-items-center rounded-xl ${color}`}><Icon size={19} /></span></div></article>)}
      </div>
      <div className="mt-5 rounded-2xl border border-slate-200 bg-white p-4 sm:p-5"><div className="flex flex-col gap-3 xl:flex-row"><label className="relative min-w-0 flex-1"><span className="sr-only">Search purchases</span><Search className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} className="h-11 w-full rounded-xl border border-slate-200 bg-slate-50 pl-10 pr-4 text-sm outline-none focus:border-sky-400 focus:bg-white focus:ring-4 focus:ring-sky-100" placeholder="Search invoice or product" /></label><select aria-label="Filter purchase status" value={status} onChange={(event) => setStatus(event.target.value)} className="h-11 rounded-xl border border-slate-200 bg-white px-4 text-sm font-semibold text-slate-600"><option>All status</option><option>Successful</option><option>Pending</option><option>Refunded</option></select><select aria-label="Filter product type" value={type} onChange={(event) => setType(event.target.value)} className="h-11 rounded-xl border border-slate-200 bg-white px-4 text-sm font-semibold text-slate-600"><option>All products</option><option>Course</option><option>Ebook</option></select></div></div>
      <div className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[920px] text-left"><thead className="border-b border-slate-200 bg-slate-50/80 text-[10px] font-extrabold uppercase tracking-[.12em] text-slate-500"><tr><th className="px-5 py-4">Invoice</th><th className="px-5 py-4">Product</th><th className="px-5 py-4">Type</th><th className="px-5 py-4">Purchase date</th><th className="px-5 py-4">Amount</th><th className="px-5 py-4">Status</th><th className="px-5 py-4 text-right">Action</th></tr></thead><tbody className="divide-y divide-slate-100 text-sm">{filtered.map((purchase) => <tr key={purchase.id} className="transition hover:bg-sky-50/30"><td className="px-5 py-4 font-bold text-[#155EAA]">{purchase.invoice}</td><td className="max-w-[240px] px-5 py-4"><p className="truncate font-bold text-slate-700">{purchase.productName}</p></td><td className="px-5 py-4 text-slate-500">{purchase.productType}</td><td className="px-5 py-4 text-slate-500">{purchase.purchaseDate}</td><td className="px-5 py-4 font-bold text-slate-700">{formatRupiah(purchase.amount)}</td><td className="px-5 py-4"><span className={`inline-flex rounded-full px-2.5 py-1 text-[10px] font-extrabold ring-1 ring-inset ${statusStyle[purchase.status]}`}>{purchase.status}</span></td><td className="px-5 py-4 text-right"><button onClick={() => setSelected(purchase)} className="inline-flex items-center gap-1.5 rounded-lg px-3 py-2 text-xs font-bold text-[#155EAA] hover:bg-sky-50"><Eye size={14} />View detail</button></td></tr>)}</tbody></table></div>{!filtered.length && <div className="py-14 text-center"><RotateCcw className="mx-auto text-slate-300" size={36} /><h2 className="mt-3 font-extrabold text-[#0B2D5C]">No transactions found</h2><p className="mt-1 text-sm text-slate-500">Try changing your search or filters.</p></div>}<div className="flex items-center justify-between border-t border-slate-100 px-5 py-4 text-xs text-slate-500"><span>Showing {filtered.length} of {purchases.length} transactions</span><span>Page 1 of 1</span></div></div>
      {selected && <div className="fixed inset-0 z-[70] grid place-items-center bg-[#071E3E]/55 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="purchase-title"><div className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#155EAA]">Transaction details</p><h2 id="purchase-title" className="mt-2 text-xl font-black text-[#0B2D5C]">{selected.invoice}</h2></div><button aria-label="Close transaction details" onClick={() => setSelected(null)} className="grid h-9 w-9 place-items-center rounded-xl bg-slate-100 text-slate-500"><X size={18} /></button></div><div className="mt-6 rounded-2xl border border-slate-100 bg-slate-50 p-4"><p className="text-xs text-slate-400">Product</p><p className="mt-1 font-extrabold text-slate-800">{selected.productName}</p><div className="mt-4 grid grid-cols-2 gap-4 text-sm"><div><p className="text-xs text-slate-400">Purchase date</p><p className="mt-1 font-bold text-slate-700">{selected.purchaseDate}</p></div><div><p className="text-xs text-slate-400">Product type</p><p className="mt-1 font-bold text-slate-700">{selected.productType}</p></div><div><p className="text-xs text-slate-400">Amount</p><p className="mt-1 font-bold text-slate-700">{formatRupiah(selected.amount)}</p></div><div><p className="text-xs text-slate-400">Status</p><span className={`mt-1 inline-flex rounded-full px-2.5 py-1 text-[10px] font-extrabold ring-1 ring-inset ${statusStyle[selected.status]}`}>{selected.status}</span></div></div></div><button onClick={receipt} disabled={selected.status !== "Successful"} className="mt-5 flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-[#0B2D5C] text-sm font-extrabold text-white disabled:bg-slate-200 disabled:text-slate-400"><Download size={16} />{selected.status === "Successful" ? "Download Receipt" : "Receipt unavailable"}</button></div></div>}
      {toast && <div role="status" className="fixed bottom-5 right-5 z-[80] rounded-xl bg-[#0B2D5C] px-4 py-3 text-sm font-semibold text-white shadow-xl">{toast}</div>}
    </>
  );
}
